import { Movie } from '@/types';

export const featuredMovie: Movie = {
  id: '1',
  title: 'Interstellar Odyssey',
  description:
    'When Earth faces an unprecedented climate catastrophe, a team of elite astronauts embarks on a daring mission through a newly discovered wormhole near Saturn. Racing against time and the laws of physics, they must find a new home for humanity before all hope is lost.',
  thumbnailUrl: '',
  backdropUrl: '',
  year: 2024,
  rating: '8.7',
  duration: '2h 49m',
  genre: ['Sci-Fi', 'Adventure', 'Drama'],
  type: 'movie',
  matchPercent: 97,
  ageRating: 'PG-13',
  color: '#0a0a2e',
  colorEnd: '#1a1a5e',
};

export const trendingNow: Movie[] = [
  {
    id: '2',
    title: 'Dark Horizons',
    description: 'A detective uncovers a vast conspiracy that reaches the highest levels of government.',
    thumbnailUrl: '',
    backdropUrl: '',
    year: 2024,
    rating: '8.2',
    duration: '1h 58m',
    genre: ['Thriller', 'Crime'],
    type: 'movie',
    matchPercent: 94,
    ageRating: 'R',
    color: '#1a0a0a',
    colorEnd: '#3d1515',
  },
  {
    id: '3',
    title: 'The Last Kingdom',
    description: 'An epic tale of survival, loyalty, and betrayal in a medieval world torn apart by war.',
    thumbnailUrl: '',
    backdropUrl: '',
    year: 2023,
    rating: '8.5',
    duration: '2h 12m',
    genre: ['Drama', 'History'],
    type: 'movie',
    matchPercent: 91,
    ageRating: 'TV-MA',
    color: '#1a1200',
    colorEnd: '#3d2b00',
  },
  {
    id: '4',
    title: 'Neon Requiem',
    description: 'In a rain-soaked cyberpunk city, a rogue AI develops consciousness and seeks freedom.',
    thumbnailUrl: '',
    backdropUrl: '',
    year: 2024,
    rating: '7.9',
    duration: '1h 45m',
    genre: ['Sci-Fi', 'Action'],
    type: 'movie',
    matchPercent: 88,
    ageRating: 'R',
    color: '#001a1a',
    colorEnd: '#003d3d',
  },
  {
    id: '5',
    title: 'Wildfire',
    description: 'A firefighter battles both raging wildfires and personal demons in the American West.',
    thumbnailUrl: '',
    backdropUrl: '',
    year: 2024,
    rating: '7.6',
    duration: '1h 52m',
    genre: ['Drama', 'Action'],
    type: 'movie',
    matchPercent: 85,
    ageRating: 'PG-13',
    color: '#1a0800',
    colorEnd: '#4d1800',
  },
  {
    id: '6',
    title: 'The Quiet Storm',
    description: 'A retired spy is pulled back into the shadows when her daughter goes missing in Eastern Europe.',
    thumbnailUrl: '',
    backdropUrl: '',
    year: 2023,
    rating: '8.0',
    duration: '2h 05m',
    genre: ['Thriller', 'Action'],
    type: 'movie',
    matchPercent: 92,
    ageRating: 'R',
    color: '#0a0a1a',
    colorEnd: '#1a1a3d',
  },
  {
    id: '7',
    title: 'Echoes of Tomorrow',
    description: 'A scientist discovers she can send messages to her past self, but every change has consequences.',
    thumbnailUrl: '',
    backdropUrl: '',
    year: 2024,
    rating: '8.3',
    duration: '1h 58m',
    genre: ['Sci-Fi', 'Drama'],
    type: 'movie',
    matchPercent: 96,
    ageRating: 'PG-13',
    color: '#001a0a',
    colorEnd: '#003d1a',
  },
  {
    id: '8',
    title: 'Broken Compass',
    description: 'Three strangers stranded in the Alaskan wilderness must work together to survive.',
    thumbnailUrl: '',
    backdropUrl: '',
    year: 2023,
    rating: '7.7',
    duration: '1h 40m',
    genre: ['Adventure', 'Survival'],
    type: 'movie',
    matchPercent: 83,
    ageRating: 'PG-13',
    color: '#0a1a00',
    colorEnd: '#1a3d00',
  },
];

export const topRated: Movie[] = [
  {
    id: '9',
    title: 'The Grand Illusion',
    description: 'A masterful exploration of class, nationality, and humanity during the First World War.',
    thumbnailUrl: '',
    backdropUrl: '',
    year: 2022,
    rating: '9.1',
    duration: '2h 34m',
    genre: ['Drama', 'War'],
    type: 'movie',
    matchPercent: 98,
    ageRating: 'PG',
    color: '#1a1000',
    colorEnd: '#3d2500',
  },
  {
    id: '10',
    title: 'Midnight in Lisbon',
    description: 'A jazz musician falls in love with a mysterious woman who may not be from this time.',
    thumbnailUrl: '',
    backdropUrl: '',
    year: 2023,
    rating: '8.8',
    duration: '1h 55m',
    genre: ['Romance', 'Fantasy'],
    type: 'movie',
    matchPercent: 90,
    ageRating: 'PG-13',
    color: '#1a0a1a',
    colorEnd: '#3d1a3d',
  },
  {
    id: '11',
    title: 'The Cartographer',
    description: 'An obsessive mapmaker in 16th century Portugal charts unknown territories at great personal cost.',
    thumbnailUrl: '',
    backdropUrl: '',
    year: 2022,
    rating: '8.9',
    duration: '2h 18m',
    genre: ['Drama', 'History'],
    type: 'movie',
    matchPercent: 93,
    ageRating: 'PG-13',
    color: '#1a1500',
    colorEnd: '#3d3000',
  },
  {
    id: '12',
    title: 'Parallel Lines',
    description: 'Two strangers living in parallel universes discover they share the same soul.',
    thumbnailUrl: '',
    backdropUrl: '',
    year: 2024,
    rating: '8.6',
    duration: '2h 02m',
    genre: ['Sci-Fi', 'Romance'],
    type: 'movie',
    matchPercent: 95,
    ageRating: 'PG-13',
    color: '#00101a',
    colorEnd: '#00253d',
  },
  {
    id: '13',
    title: 'The Weight of Gold',
    description: 'A documentary following Olympic athletes as they navigate the mental health challenges of elite sport.',
    thumbnailUrl: '',
    backdropUrl: '',
    year: 2023,
    rating: '9.0',
    duration: '1h 38m',
    genre: ['Documentary', 'Sport'],
    type: 'movie',
    matchPercent: 97,
    ageRating: 'PG',
    color: '#1a1500',
    colorEnd: '#4d3d00',
  },
  {
    id: '14',
    title: 'Saltwater',
    description: 'A marine biologist uncovers a shocking truth about ocean pollution that threatens all life on Earth.',
    thumbnailUrl: '',
    backdropUrl: '',
    year: 2024,
    rating: '8.4',
    duration: '1h 48m',
    genre: ['Documentary', 'Drama'],
    type: 'movie',
    matchPercent: 89,
    ageRating: 'PG',
    color: '#001520',
    colorEnd: '#003050',
  },
  {
    id: '15',
    title: 'Crimson Tide Rising',
    description: 'A political thriller set aboard a nuclear submarine where the captain and XO clash over a launch order.',
    thumbnailUrl: '',
    backdropUrl: '',
    year: 2023,
    rating: '8.7',
    duration: '2h 08m',
    genre: ['Thriller', 'Drama'],
    type: 'movie',
    matchPercent: 94,
    ageRating: 'R',
    color: '#0a0015',
    colorEnd: '#1a0030',
  },
  {
    id: '16',
    title: 'The Orchard',
    description: 'Three generations of a family farm face extinction as corporate agriculture closes in.',
    thumbnailUrl: '',
    backdropUrl: '',
    year: 2022,
    rating: '8.5',
    duration: '1h 52m',
    genre: ['Drama', 'Family'],
    type: 'movie',
    matchPercent: 88,
    ageRating: 'PG',
    color: '#0a1500',
    colorEnd: '#1a3000',
  },
];

export const actionMovies: Movie[] = [
  {
    id: '17',
    title: 'Iron Fist Protocol',
    description: 'A special forces operative goes rogue to expose a black-ops program targeting civilians.',
    thumbnailUrl: '',
    backdropUrl: '',
    year: 2024,
    rating: '7.8',
    duration: '2h 05m',
    genre: ['Action', 'Thriller'],
    type: 'movie',
    matchPercent: 87,
    ageRating: 'R',
    color: '#1a0000',
    colorEnd: '#4d0000',
  },
  {
    id: '18',
    title: 'Velocity',
    description: 'A street racer is recruited by Interpol to infiltrate a global smuggling ring.',
    thumbnailUrl: '',
    backdropUrl: '',
    year: 2023,
    rating: '7.4',
    duration: '1h 58m',
    genre: ['Action', 'Crime'],
    type: 'movie',
    matchPercent: 82,
    ageRating: 'PG-13',
    color: '#1a0a00',
    colorEnd: '#4d1a00',
  },
  {
    id: '19',
    title: 'Siege of Kandahar',
    description: 'Based on true events, a small team of soldiers defends a remote outpost against overwhelming odds.',
    thumbnailUrl: '',
    backdropUrl: '',
    year: 2024,
    rating: '8.1',
    duration: '2h 15m',
    genre: ['Action', 'War'],
    type: 'movie',
    matchPercent: 91,
    ageRating: 'R',
    color: '#0a0800',
    colorEnd: '#2a2000',
  },
  {
    id: '20',
    title: 'Phantom Strike',
    description: 'An elite hacker and a disgraced soldier team up to prevent a cyberattack on global infrastructure.',
    thumbnailUrl: '',
    backdropUrl: '',
    year: 2024,
    rating: '7.6',
    duration: '1h 52m',
    genre: ['Action', 'Sci-Fi'],
    type: 'movie',
    matchPercent: 85,
    ageRating: 'PG-13',
    color: '#000a1a',
    colorEnd: '#00153d',
  },
  {
    id: '21',
    title: 'Reckoning Day',
    description: 'A vigilante judge takes the law into her own hands when the justice system fails her community.',
    thumbnailUrl: '',
    backdropUrl: '',
    year: 2023,
    rating: '7.9',
    duration: '2h 00m',
    genre: ['Action', 'Drama'],
    type: 'movie',
    matchPercent: 88,
    ageRating: 'R',
    color: '#150010',
    colorEnd: '#350025',
  },
  {
    id: '22',
    title: 'Arctic Thunder',
    description: 'A NATO rescue mission in the Arctic turns into a deadly cat-and-mouse game with Russian operatives.',
    thumbnailUrl: '',
    backdropUrl: '',
    year: 2024,
    rating: '7.5',
    duration: '1h 48m',
    genre: ['Action', 'Thriller'],
    type: 'movie',
    matchPercent: 84,
    ageRating: 'R',
    color: '#001015',
    colorEnd: '#002535',
  },
];

export const comedyMovies: Movie[] = [
  {
    id: '23',
    title: 'The Accidental CEO',
    description: 'A janitor accidentally gets promoted to CEO and must navigate the absurd world of corporate America.',
    thumbnailUrl: '',
    backdropUrl: '',
    year: 2024,
    rating: '7.3',
    duration: '1h 42m',
    genre: ['Comedy', 'Drama'],
    type: 'movie',
    matchPercent: 86,
    ageRating: 'PG-13',
    color: '#1a1500',
    colorEnd: '#4d3d00',
  },
  {
    id: '24',
    title: 'Wedding Crashers: Reunion',
    description: 'Two middle-aged friends relive their glory days crashing weddings, with hilariously unexpected results.',
    thumbnailUrl: '',
    backdropUrl: '',
    year: 2023,
    rating: '7.1',
    duration: '1h 55m',
    genre: ['Comedy', 'Romance'],
    type: 'movie',
    matchPercent: 80,
    ageRating: 'R',
    color: '#1a0a15',
    colorEnd: '#4d1a35',
  },
  {
    id: '25',
    title: 'Grandma Goes to Space',
    description: 'An 80-year-old grandmother wins a lottery ticket to the first commercial space station.',
    thumbnailUrl: '',
    backdropUrl: '',
    year: 2024,
    rating: '7.5',
    duration: '1h 38m',
    genre: ['Comedy', 'Sci-Fi'],
    type: 'movie',
    matchPercent: 84,
    ageRating: 'PG',
    color: '#001020',
    colorEnd: '#002040',
  },
  {
    id: '26',
    title: 'The Perfect Roommate',
    description: 'A type-A lawyer and a free-spirited artist are forced to share an apartment in New York City.',
    thumbnailUrl: '',
    backdropUrl: '',
    year: 2023,
    rating: '7.0',
    duration: '1h 45m',
    genre: ['Comedy', 'Romance'],
    type: 'movie',
    matchPercent: 79,
    ageRating: 'PG-13',
    color: '#150015',
    colorEnd: '#350035',
  },
  {
    id: '27',
    title: 'Chef Wars',
    description: 'A Michelin-star chef and a food truck owner compete for the same restaurant space in Paris.',
    thumbnailUrl: '',
    backdropUrl: '',
    year: 2024,
    rating: '7.4',
    duration: '1h 50m',
    genre: ['Comedy', 'Drama'],
    type: 'movie',
    matchPercent: 83,
    ageRating: 'PG-13',
    color: '#1a0800',
    colorEnd: '#4d1800',
  },
  {
    id: '28',
    title: 'Dial M for Mayhem',
    description: 'A retired hitman accidentally becomes a life coach and must keep his past a secret from his clients.',
    thumbnailUrl: '',
    backdropUrl: '',
    year: 2023,
    rating: '7.6',
    duration: '1h 52m',
    genre: ['Comedy', 'Crime'],
    type: 'movie',
    matchPercent: 87,
    ageRating: 'R',
    color: '#0a0a0a',
    colorEnd: '#252525',
  },
];

export const documentaries: Movie[] = [
  {
    id: '29',
    title: 'The Last Glacier',
    description: 'A stunning visual journey documenting the rapid disappearance of the world\'s glaciers.',
    thumbnailUrl: '',
    backdropUrl: '',
    year: 2024,
    rating: '8.6',
    duration: '1h 32m',
    genre: ['Documentary', 'Nature'],
    type: 'movie',
    matchPercent: 93,
    ageRating: 'G',
    color: '#001520',
    colorEnd: '#003050',
  },
  {
    id: '30',
    title: 'Inside the Algorithm',
    description: 'An investigation into how social media algorithms are reshaping democracy and human behavior.',
    thumbnailUrl: '',
    backdropUrl: '',
    year: 2023,
    rating: '8.8',
    duration: '1h 48m',
    genre: ['Documentary', 'Technology'],
    type: 'movie',
    matchPercent: 96,
    ageRating: 'PG',
    color: '#000a1a',
    colorEnd: '#00153d',
  },
  {
    id: '31',
    title: 'The Forgotten War',
    description: 'Untold stories from veterans of conflicts that never made the front pages of history books.',
    thumbnailUrl: '',
    backdropUrl: '',
    year: 2022,
    rating: '8.9',
    duration: '2h 05m',
    genre: ['Documentary', 'History'],
    type: 'movie',
    matchPercent: 95,
    ageRating: 'TV-14',
    color: '#100800',
    colorEnd: '#2a1500',
  },
  {
    id: '32',
    title: 'Deep Ocean',
    description: 'Cutting-edge submersibles reveal never-before-seen creatures in the deepest parts of the ocean.',
    thumbnailUrl: '',
    backdropUrl: '',
    year: 2024,
    rating: '8.7',
    duration: '1h 55m',
    genre: ['Documentary', 'Nature'],
    type: 'movie',
    matchPercent: 94,
    ageRating: 'G',
    color: '#000510',
    colorEnd: '#000a25',
  },
  {
    id: '33',
    title: 'The Billionaire Blueprint',
    description: 'A critical look at how the ultra-wealthy accumulate power and influence global policy.',
    thumbnailUrl: '',
    backdropUrl: '',
    year: 2023,
    rating: '8.4',
    duration: '1h 42m',
    genre: ['Documentary', 'Politics'],
    type: 'movie',
    matchPercent: 91,
    ageRating: 'PG',
    color: '#0a0800',
    colorEnd: '#201800',
  },
  {
    id: '34',
    title: 'Rewilding Earth',
    description: 'Scientists and activists work to restore natural ecosystems destroyed by human activity.',
    thumbnailUrl: '',
    backdropUrl: '',
    year: 2024,
    rating: '8.5',
    duration: '1h 38m',
    genre: ['Documentary', 'Nature'],
    type: 'movie',
    matchPercent: 92,
    ageRating: 'G',
    color: '#001500',
    colorEnd: '#003000',
  },
];

export const tvShows: Movie[] = [
  {
    id: '35',
    title: 'Sovereign',
    description: 'A political drama following the inner workings of a fictional European monarchy facing a constitutional crisis.',
    thumbnailUrl: '',
    backdropUrl: '',
    year: 2023,
    rating: '8.9',
    duration: '4 Seasons',
    genre: ['Drama', 'Politics'],
    type: 'tv',
    matchPercent: 97,
    ageRating: 'TV-MA',
    color: '#1a1200',
    colorEnd: '#3d2b00',
  },
  {
    id: '36',
    title: 'Cipher',
    description: 'A cryptographer at the NSA discovers a hidden message in global financial transactions that points to an imminent attack.',
    thumbnailUrl: '',
    backdropUrl: '',
    year: 2024,
    rating: '8.6',
    duration: '2 Seasons',
    genre: ['Thriller', 'Crime'],
    type: 'tv',
    matchPercent: 94,
    ageRating: 'TV-MA',
    color: '#000a15',
    colorEnd: '#00152a',
  },
  {
    id: '37',
    title: 'The Frontier',
    description: 'A sweeping Western epic following three families competing for land and survival in 1880s Montana.',
    thumbnailUrl: '',
    backdropUrl: '',
    year: 2022,
    rating: '8.7',
    duration: '3 Seasons',
    genre: ['Drama', 'Western'],
    type: 'tv',
    matchPercent: 95,
    ageRating: 'TV-MA',
    color: '#1a0a00',
    colorEnd: '#3d1500',
  },
  {
    id: '38',
    title: 'Quantum Break',
    description: 'A physicist accidentally creates a time loop and must relive the same catastrophic day until she finds the solution.',
    thumbnailUrl: '',
    backdropUrl: '',
    year: 2024,
    rating: '8.3',
    duration: '1 Season',
    genre: ['Sci-Fi', 'Mystery'],
    type: 'tv',
    matchPercent: 91,
    ageRating: 'TV-14',
    color: '#001020',
    colorEnd: '#002040',
  },
  {
    id: '39',
    title: 'The Syndicate',
    description: 'An undercover detective infiltrates a powerful organized crime family in Chicago over five years.',
    thumbnailUrl: '',
    backdropUrl: '',
    year: 2021,
    rating: '9.0',
    duration: '5 Seasons',
    genre: ['Crime', 'Drama'],
    type: 'tv',
    matchPercent: 98,
    ageRating: 'TV-MA',
    color: '#0a0000',
    colorEnd: '#200000',
  },
  {
    id: '40',
    title: 'Bloom',
    description: 'A botanist in a near-future world where plants have developed rudimentary intelligence tries to communicate with them.',
    thumbnailUrl: '',
    backdropUrl: '',
    year: 2024,
    rating: '8.1',
    duration: '1 Season',
    genre: ['Sci-Fi', 'Drama'],
    type: 'tv',
    matchPercent: 89,
    ageRating: 'TV-14',
    color: '#001500',
    colorEnd: '#003000',
  },
  {
    id: '41',
    title: 'Midnight Shift',
    description: 'Dark comedy following the overnight staff at a struggling urban hospital dealing with impossible situations.',
    thumbnailUrl: '',
    backdropUrl: '',
    year: 2023,
    rating: '8.4',
    duration: '2 Seasons',
    genre: ['Comedy', 'Drama'],
    type: 'tv',
    matchPercent: 92,
    ageRating: 'TV-MA',
    color: '#0a0015',
    colorEnd: '#150025',
  },
  {
    id: '42',
    title: 'The Architect',
    description: 'A visionary architect battles corrupt city officials and greedy developers to build affordable housing in San Francisco.',
    thumbnailUrl: '',
    backdropUrl: '',
    year: 2023,
    rating: '8.2',
    duration: '2 Seasons',
    genre: ['Drama', 'Politics'],
    type: 'tv',
    matchPercent: 90,
    ageRating: 'TV-14',
    color: '#100a00',
    colorEnd: '#251500',
  },
  {
    id: '43',
    title: 'Wavelength',
    description: 'A radio host in a small coastal town begins receiving transmissions from a ship that disappeared 30 years ago.',
    thumbnailUrl: '',
    backdropUrl: '',
    year: 2024,
    rating: '8.5',
    duration: '1 Season',
    genre: ['Mystery', 'Thriller'],
    type: 'tv',
    matchPercent: 93,
    ageRating: 'TV-14',
    color: '#001015',
    colorEnd: '#002030',
  },
  {
    id: '44',
    title: 'Roots & Routes',
    description: 'A travel documentary series exploring the food, culture, and history of overlooked destinations worldwide.',
    thumbnailUrl: '',
    backdropUrl: '',
    year: 2024,
    rating: '8.8',
    duration: '3 Seasons',
    genre: ['Documentary', 'Travel'],
    type: 'tv',
    matchPercent: 96,
    ageRating: 'TV-G',
    color: '#1a0800',
    colorEnd: '#3d1500',
  },
  {
    id: '45',
    title: 'Glass Houses',
    description: 'A tech billionaire\'s family implodes when a whistleblower exposes the dark secrets behind their empire.',
    thumbnailUrl: '',
    backdropUrl: '',
    year: 2023,
    rating: '8.6',
    duration: '2 Seasons',
    genre: ['Drama', 'Thriller'],
    type: 'tv',
    matchPercent: 94,
    ageRating: 'TV-MA',
    color: '#050510',
    colorEnd: '#0a0a25',
  },
  {
    id: '46',
    title: 'The Naturalist',
    description: 'A wildlife biologist documents extraordinary animal behavior in remote corners of the world.',
    thumbnailUrl: '',
    backdropUrl: '',
    year: 2024,
    rating: '8.9',
    duration: '2 Seasons',
    genre: ['Documentary', 'Nature'],
    type: 'tv',
    matchPercent: 97,
    ageRating: 'TV-G',
    color: '#001000',
    colorEnd: '#002500',
  },
];

export const allMovies: Movie[] = [
  ...trendingNow,
  ...topRated,
  ...actionMovies,
  ...comedyMovies,
  ...documentaries,
];

export const myListMovies: Movie[] = [
  trendingNow[0],
  topRated[1],
  actionMovies[2],
  documentaries[0],
];
