import { Movie, MovieRow } from '@/types';

const MOVIES: Movie[] = [
  {
    id: '1',
    title: 'Stranger Things',
    description: 'When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl.',
    thumbnailUrl: 'https://picsum.photos/seed/stranger/400/225',
    backdropUrl: 'https://picsum.photos/seed/strangerbg/1920/1080',
    year: 2016,
    rating: 'TV-14',
    duration: '4 Seasons',
    matchScore: 97,
    genres: ['Drama', 'Fantasy', 'Horror'],
    type: 'tv',
    badge: 'TOP 10',
    isFeatured: true,
  },
  {
    id: '2',
    title: 'The Dark Knight',
    description: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
    thumbnailUrl: 'https://picsum.photos/seed/darkknight/400/225',
    backdropUrl: 'https://picsum.photos/seed/darkknightbg/1920/1080',
    year: 2008,
    rating: 'PG-13',
    duration: '2h 32m',
    matchScore: 99,
    genres: ['Action', 'Crime', 'Drama'],
    type: 'movie',
  },
  {
    id: '3',
    title: 'Inception',
    description: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
    thumbnailUrl: 'https://picsum.photos/seed/inception/400/225',
    backdropUrl: 'https://picsum.photos/seed/inceptionbg/1920/1080',
    year: 2010,
    rating: 'PG-13',
    duration: '2h 28m',
    matchScore: 95,
    genres: ['Action', 'Sci-Fi', 'Thriller'],
    type: 'movie',
  },
  {
    id: '4',
    title: 'Breaking Bad',
    description: 'A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family\'s future.',
    thumbnailUrl: 'https://picsum.photos/seed/breakingbad/400/225',
    backdropUrl: 'https://picsum.photos/seed/breakingbadbg/1920/1080',
    year: 2008,
    rating: 'TV-MA',
    duration: '5 Seasons',
    matchScore: 98,
    genres: ['Crime', 'Drama', 'Thriller'],
    type: 'tv',
  },
  {
    id: '5',
    title: 'The Witcher',
    description: 'Geralt of Rivia, a solitary monster hunter, struggles to find his place in a world where people often prove more wicked than beasts.',
    thumbnailUrl: 'https://picsum.photos/seed/witcher/400/225',
    backdropUrl: 'https://picsum.photos/seed/witcherbg/1920/1080',
    year: 2019,
    rating: 'TV-MA',
    duration: '3 Seasons',
    matchScore: 88,
    genres: ['Action', 'Fantasy', 'Drama'],
    type: 'tv',
  },
  {
    id: '6',
    title: 'Interstellar',
    description: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
    thumbnailUrl: 'https://picsum.photos/seed/interstellar/400/225',
    backdropUrl: 'https://picsum.photos/seed/interstellarbg/1920/1080',
    year: 2014,
    rating: 'PG-13',
    duration: '2h 49m',
    matchScore: 94,
    genres: ['Adventure', 'Drama', 'Sci-Fi'],
    type: 'movie',
  },
  {
    id: '7',
    title: 'Ozark',
    description: 'A financial advisor drags his family from Chicago to the Missouri Ozarks, where he must launder money to appease a drug boss.',
    thumbnailUrl: 'https://picsum.photos/seed/ozark/400/225',
    backdropUrl: 'https://picsum.photos/seed/ozarkbg/1920/1080',
    year: 2017,
    rating: 'TV-MA',
    duration: '4 Seasons',
    matchScore: 92,
    genres: ['Crime', 'Drama', 'Thriller'],
    type: 'tv',
  },
  {
    id: '8',
    title: 'The Matrix',
    description: 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
    thumbnailUrl: 'https://picsum.photos/seed/matrix/400/225',
    backdropUrl: 'https://picsum.photos/seed/matrixbg/1920/1080',
    year: 1999,
    rating: 'R',
    duration: '2h 16m',
    matchScore: 96,
    genres: ['Action', 'Sci-Fi'],
    type: 'movie',
  },
  {
    id: '9',
    title: 'Money Heist',
    description: 'An unusual group of robbers attempt to carry out the most perfect robbery in Spanish history - stealing 2.4 billion euros from the Royal Mint of Spain.',
    thumbnailUrl: 'https://picsum.photos/seed/moneyheist/400/225',
    backdropUrl: 'https://picsum.photos/seed/moneyheistbg/1920/1080',
    year: 2017,
    rating: 'TV-MA',
    duration: '5 Seasons',
    matchScore: 91,
    genres: ['Action', 'Crime', 'Mystery'],
    type: 'tv',
    badge: 'TOP 10',
  },
  {
    id: '10',
    title: 'Avengers: Endgame',
    description: 'After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos\' actions and restore balance to the universe.',
    thumbnailUrl: 'https://picsum.photos/seed/avengers/400/225',
    backdropUrl: 'https://picsum.photos/seed/avengersbg/1920/1080',
    year: 2019,
    rating: 'PG-13',
    duration: '3h 1m',
    matchScore: 93,
    genres: ['Action', 'Adventure', 'Drama'],
    type: 'movie',
  },
  {
    id: '11',
    title: 'Squid Game',
    description: 'Hundreds of cash-strapped players accept a strange invitation to compete in children\'s games. Inside, a tempting prize awaits with deadly high stakes.',
    thumbnailUrl: 'https://picsum.photos/seed/squidgame/400/225',
    backdropUrl: 'https://picsum.photos/seed/squidgamebg/1920/1080',
    year: 2021,
    rating: 'TV-MA',
    duration: '2 Seasons',
    matchScore: 97,
    genres: ['Action', 'Drama', 'Mystery'],
    type: 'tv',
    badge: 'TOP 10',
  },
  {
    id: '12',
    title: 'Dune',
    description: 'Feature adaptation of Frank Herbert\'s science fiction novel about the son of a noble family entrusted with the protection of the most valuable asset in the galaxy.',
    thumbnailUrl: 'https://picsum.photos/seed/dune/400/225',
    backdropUrl: 'https://picsum.photos/seed/dunebg/1920/1080',
    year: 2021,
    rating: 'PG-13',
    duration: '2h 35m',
    matchScore: 90,
    genres: ['Adventure', 'Drama', 'Sci-Fi'],
    type: 'movie',
  },
  {
    id: '13',
    title: 'The Crown',
    description: 'Follows the political rivalries and romance of Queen Elizabeth II\'s reign and the events that shaped the second half of the twentieth century.',
    thumbnailUrl: 'https://picsum.photos/seed/thecrown/400/225',
    backdropUrl: 'https://picsum.photos/seed/thecrownbg/1920/1080',
    year: 2016,
    rating: 'TV-MA',
    duration: '6 Seasons',
    matchScore: 89,
    genres: ['Biography', 'Drama', 'History'],
    type: 'tv',
  },
  {
    id: '14',
    title: 'Parasite',
    description: 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.',
    thumbnailUrl: 'https://picsum.photos/seed/parasite/400/225',
    backdropUrl: 'https://picsum.photos/seed/parasitebg/1920/1080',
    year: 2019,
    rating: 'R',
    duration: '2h 12m',
    matchScore: 96,
    genres: ['Comedy', 'Drama', 'Thriller'],
    type: 'movie',
  },
  {
    id: '15',
    title: 'Wednesday',
    description: 'Smart, sarcastic and a little dead inside, Wednesday Addams investigates a murder spree while making new friends and enemies at Nevermore Academy.',
    thumbnailUrl: 'https://picsum.photos/seed/wednesday/400/225',
    backdropUrl: 'https://picsum.photos/seed/wednesdaybg/1920/1080',
    year: 2022,
    rating: 'TV-14',
    duration: '2 Seasons',
    matchScore: 94,
    genres: ['Comedy', 'Fantasy', 'Horror'],
    type: 'tv',
    badge: 'NEW',
  },
  {
    id: '16',
    title: 'Oppenheimer',
    description: 'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb during World War II.',
    thumbnailUrl: 'https://picsum.photos/seed/oppenheimer/400/225',
    backdropUrl: 'https://picsum.photos/seed/oppenheimerbg/1920/1080',
    year: 2023,
    rating: 'R',
    duration: '3h',
    matchScore: 95,
    genres: ['Biography', 'Drama', 'History'],
    type: 'movie',
    badge: 'NEW',
  },
  {
    id: '17',
    title: 'Black Mirror',
    description: 'An anthology series exploring a twisted, high-tech multiverse where humanity\'s greatest innovations and darkest instincts collide.',
    thumbnailUrl: 'https://picsum.photos/seed/blackmirror/400/225',
    backdropUrl: 'https://picsum.photos/seed/blackmirrorbg/1920/1080',
    year: 2011,
    rating: 'TV-MA',
    duration: '6 Seasons',
    matchScore: 91,
    genres: ['Drama', 'Sci-Fi', 'Thriller'],
    type: 'tv',
  },
  {
    id: '18',
    title: 'Barbie',
    description: 'Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.',
    thumbnailUrl: 'https://picsum.photos/seed/barbie/400/225',
    backdropUrl: 'https://picsum.photos/seed/barbiebg/1920/1080',
    year: 2023,
    rating: 'PG-13',
    duration: '1h 54m',
    matchScore: 87,
    genres: ['Adventure', 'Comedy', 'Fantasy'],
    type: 'movie',
    badge: 'NEW',
  },
  {
    id: '19',
    title: 'Peaky Blinders',
    description: 'A gangster family epic set in 1900s England, centering on a gang who sew razor blades in the peaks of their caps, and their fierce boss Tommy Shelby.',
    thumbnailUrl: 'https://picsum.photos/seed/peakyblinders/400/225',
    backdropUrl: 'https://picsum.photos/seed/peakyblinderbg/1920/1080',
    year: 2013,
    rating: 'TV-MA',
    duration: '6 Seasons',
    matchScore: 96,
    genres: ['Crime', 'Drama'],
    type: 'tv',
  },
  {
    id: '20',
    title: 'The Social Network',
    description: 'As Harvard student Mark Zuckerberg creates the social networking site that would become known as Facebook, he is sued by the twins who claimed he stole their idea, and by the co-founder who was later squeezed out of the business.',
    thumbnailUrl: 'https://picsum.photos/seed/socialnetwork/400/225',
    backdropUrl: 'https://picsum.photos/seed/socialnetworkbg/1920/1080',
    year: 2010,
    rating: 'PG-13',
    duration: '2h',
    matchScore: 93,
    genres: ['Biography', 'Drama'],
    type: 'movie',
  },
];

export function getFeaturedMovie(): Movie {
  return MOVIES.find((m) => m.isFeatured) || MOVIES[0];
}

export function getAllMovies(): Movie[] {
  return MOVIES.filter((m) => m.type === 'movie');
}

export function getAllTVShows(): Movie[] {
  return MOVIES.filter((m) => m.type === 'tv');
}

export function searchMovies(query: string): Movie[] {
  const q = query.toLowerCase();
  return MOVIES.filter(
    (m) =>
      m.title.toLowerCase().includes(q) ||
      m.description.toLowerCase().includes(q) ||
      m.genres.some((g) => g.toLowerCase().includes(q))
  );
}

export function getMyListMovies(): Movie[] {
  return MOVIES.slice(0, 6);
}

export function getMovieRows(): MovieRow[] {
  return [
    {
      id: 'trending',
      title: 'Trending Now',
      movies: MOVIES.slice(0, 10),
    },
    {
      id: 'new-releases',
      title: 'New Releases',
      movies: MOVIES.filter((m) => m.badge === 'NEW' || m.year >= 2021),
    },
    {
      id: 'top10',
      title: 'Top 10 on StreamFlix Today',
      movies: MOVIES.filter((m) => m.badge === 'TOP 10' || m.matchScore >= 93).slice(0, 10),
    },
    {
      id: 'action',
      title: 'Action & Adventure',
      movies: MOVIES.filter((m) => m.genres.includes('Action')),
    },
    {
      id: 'drama',
      title: 'Award-Winning Dramas',
      movies: MOVIES.filter((m) => m.genres.includes('Drama')),
    },
    {
      id: 'scifi',
      title: 'Sci-Fi & Fantasy',
      movies: MOVIES.filter((m) => m.genres.includes('Sci-Fi') || m.genres.includes('Fantasy')),
    },
    {
      id: 'crime',
      title: 'Crime & Thriller',
      movies: MOVIES.filter((m) => m.genres.includes('Crime') || m.genres.includes('Thriller')),
    },
  ];
}
