import { Title } from '@/types';

export const FEATURED_MOVIE: Title = {
  id: 1,
  title: 'Stranger Things',
  overview:
    'When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl. A love letter to the supernatural classics of the 80s.',
  posterPath: 'https://via.placeholder.com/300x450/1a1a2e/E50914?text=Stranger+Things',
  backdropPath: 'https://via.placeholder.com/1280x720/1a1a2e/E50914?text=Stranger+Things',
  voteAverage: 8.7,
  releaseYear: 2016,
  mediaType: 'tv',
  genres: ['Drama', 'Fantasy', 'Horror'],
  maturityRating: 'TV-14',
  seasons: 4,
  isNetflixOriginal: true,
  cast: ['Millie Bobby Brown', 'Finn Wolfhard', 'Winona Ryder', 'David Harbour'],
};

export const TRENDING_NOW: Title[] = [
  {
    id: 2,
    title: 'Wednesday',
    overview:
      'Smart, sarcastic and a little dead inside, Wednesday Addams investigates a murder spree while making new friends — and foes — at Nevermore Academy.',
    posterPath: 'https://via.placeholder.com/300x450/0d0d0d/ffffff?text=Wednesday',
    backdropPath: 'https://via.placeholder.com/1280x720/0d0d0d/ffffff?text=Wednesday',
    voteAverage: 8.1,
    releaseYear: 2022,
    mediaType: 'tv',
    genres: ['Comedy', 'Fantasy', 'Mystery'],
    maturityRating: 'TV-14',
    seasons: 1,
    isNetflixOriginal: true,
    cast: ['Jenna Ortega', 'Gwendoline Christie', 'Riki Lindhome'],
  },
  {
    id: 3,
    title: 'The Crown',
    overview:
      'This drama follows the political rivalries and romance of Queen Elizabeth II\'s reign and the events that shaped the second half of the 20th century.',
    posterPath: 'https://via.placeholder.com/300x450/2c1810/d4af37?text=The+Crown',
    backdropPath: 'https://via.placeholder.com/1280x720/2c1810/d4af37?text=The+Crown',
    voteAverage: 8.6,
    releaseYear: 2016,
    mediaType: 'tv',
    genres: ['Drama', 'History'],
    maturityRating: 'TV-MA',
    seasons: 6,
    isNetflixOriginal: true,
    cast: ['Claire Foy', 'Olivia Colman', 'Imelda Staunton'],
  },
  {
    id: 4,
    title: 'Extraction',
    overview:
      'A hardened mercenary\'s mission becomes a soul-searching race to survive when he\'s sent into Bangladesh to rescue a drug lord\'s kidnapped son.',
    posterPath: 'https://via.placeholder.com/300x450/1c2833/e74c3c?text=Extraction',
    backdropPath: 'https://via.placeholder.com/1280x720/1c2833/e74c3c?text=Extraction',
    voteAverage: 6.7,
    releaseYear: 2020,
    mediaType: 'movie',
    genres: ['Action', 'Thriller'],
    maturityRating: 'R',
    duration: '1h 56m',
    isNetflixOriginal: true,
    cast: ['Chris Hemsworth', 'Rudhraksh Jaiswal', 'Randeep Hooda'],
  },
  {
    id: 5,
    title: 'Bird Box',
    overview:
      'Five years after an ominous unseen presence drives most of society to suicide, a survivor and her two children make a desperate bid to reach safety.',
    posterPath: 'https://via.placeholder.com/300x450/0a0a0a/9b59b6?text=Bird+Box',
    backdropPath: 'https://via.placeholder.com/1280x720/0a0a0a/9b59b6?text=Bird+Box',
    voteAverage: 6.6,
    releaseYear: 2018,
    mediaType: 'movie',
    genres: ['Drama', 'Horror', 'Sci-Fi'],
    maturityRating: 'R',
    duration: '2h 4m',
    isNetflixOriginal: true,
    cast: ['Sandra Bullock', 'Trevante Rhodes', 'John Malkovich'],
  },
  {
    id: 6,
    title: 'Ozark',
    overview:
      'A financial advisor drags his family from Chicago to the Missouri Ozarks, where he must launder money to appease a drug boss.',
    posterPath: 'https://via.placeholder.com/300x450/0e1117/27ae60?text=Ozark',
    backdropPath: 'https://via.placeholder.com/1280x720/0e1117/27ae60?text=Ozark',
    voteAverage: 8.4,
    releaseYear: 2017,
    mediaType: 'tv',
    genres: ['Crime', 'Drama', 'Thriller'],
    maturityRating: 'TV-MA',
    seasons: 4,
    isNetflixOriginal: true,
    cast: ['Jason Bateman', 'Laura Linney', 'Sofia Hublitz'],
  },
  {
    id: 7,
    title: 'Money Heist',
    overview:
      'Eight thieves take hostages and lock themselves in the Royal Mint of Spain as a criminal mastermind manipulates the police to carry out his plan.',
    posterPath: 'https://via.placeholder.com/300x450/8b0000/ffffff?text=Money+Heist',
    backdropPath: 'https://via.placeholder.com/1280x720/8b0000/ffffff?text=Money+Heist',
    voteAverage: 8.2,
    releaseYear: 2017,
    mediaType: 'tv',
    genres: ['Action', 'Crime', 'Drama'],
    maturityRating: 'TV-MA',
    seasons: 5,
    isNetflixOriginal: false,
    cast: ['Álvaro Morte', 'Itziar Ituño', 'Pedro Alonso'],
  },
];

export const POPULAR_MOVIES: Title[] = [
  {
    id: 8,
    title: 'The Irishman',
    overview:
      'Hitman Frank Sheeran looks back at the secrets he kept as a loyal member of the Bufalino crime family in this acclaimed drama from Martin Scorsese.',
    posterPath: 'https://via.placeholder.com/300x450/1a1a1a/c0392b?text=The+Irishman',
    backdropPath: 'https://via.placeholder.com/1280x720/1a1a1a/c0392b?text=The+Irishman',
    voteAverage: 7.8,
    releaseYear: 2019,
    mediaType: 'movie',
    genres: ['Biography', 'Crime', 'Drama'],
    maturityRating: 'R',
    duration: '3h 29m',
    isNetflixOriginal: true,
    cast: ['Robert De Niro', 'Al Pacino', 'Joe Pesci'],
  },
  {
    id: 9,
    title: 'Marriage Story',
    overview:
      'A stage director and an actress struggle through a grueling, coast-to-coast divorce that pushes them to their personal and creative extremes.',
    posterPath: 'https://via.placeholder.com/300x450/f5f5f5/333333?text=Marriage+Story',
    backdropPath: 'https://via.placeholder.com/1280x720/f5f5f5/333333?text=Marriage+Story',
    voteAverage: 7.9,
    releaseYear: 2019,
    mediaType: 'movie',
    genres: ['Comedy', 'Drama', 'Romance'],
    maturityRating: 'R',
    duration: '2h 17m',
    isNetflixOriginal: true,
    cast: ['Adam Driver', 'Scarlett Johansson', 'Laura Dern'],
  },
  {
    id: 10,
    title: 'Roma',
    overview:
      'A year in the life of a middle-class family\'s maid in Mexico City in the early 1970s. Alfonso Cuarón\'s deeply personal masterpiece.',
    posterPath: 'https://via.placeholder.com/300x450/e8e8e8/222222?text=Roma',
    backdropPath: 'https://via.placeholder.com/1280x720/e8e8e8/222222?text=Roma',
    voteAverage: 7.7,
    releaseYear: 2018,
    mediaType: 'movie',
    genres: ['Drama'],
    maturityRating: 'R',
    duration: '2h 15m',
    isNetflixOriginal: true,
    cast: ['Yalitza Aparicio', 'Marina de Tavira', 'Diego Cortina Autrey'],
  },
  {
    id: 11,
    title: 'The Power of the Dog',
    overview:
      'Charismatic rancher Phil Burbank inspires fear and awe in those around him. When his brother brings home a new wife and her son, Phil torments them until he finds himself exposed.',
    posterPath: 'https://via.placeholder.com/300x450/3d2b1f/e67e22?text=Power+of+Dog',
    backdropPath: 'https://via.placeholder.com/1280x720/3d2b1f/e67e22?text=Power+of+Dog',
    voteAverage: 6.8,
    releaseYear: 2021,
    mediaType: 'movie',
    genres: ['Drama', 'Western'],
    maturityRating: 'R',
    duration: '2h 6m',
    isNetflixOriginal: true,
    cast: ['Benedict Cumberbatch', 'Kirsten Dunst', 'Jesse Plemons'],
  },
  {
    id: 12,
    title: 'Mudbound',
    overview:
      'Two men return home from World War II to work on a farm in rural Mississippi, where they struggle to deal with racism and adjusting to civilian life.',
    posterPath: 'https://via.placeholder.com/300x450/4a3728/d4a017?text=Mudbound',
    backdropPath: 'https://via.placeholder.com/1280x720/4a3728/d4a017?text=Mudbound',
    voteAverage: 7.4,
    releaseYear: 2017,
    mediaType: 'movie',
    genres: ['Drama', 'History', 'War'],
    maturityRating: 'R',
    duration: '2h 14m',
    isNetflixOriginal: true,
    cast: ['Carey Mulligan', 'Garrett Hedlund', 'Jason Clarke'],
  },
  {
    id: 13,
    title: 'Mank',
    overview:
      '1930s Hollywood is reevaluated through the eyes of scathing social critic and alcoholic screenwriter Herman J. Mankiewicz as he races to finish the screenplay of Citizen Kane.',
    posterPath: 'https://via.placeholder.com/300x450/1c1c1c/aaaaaa?text=Mank',
    backdropPath: 'https://via.placeholder.com/1280x720/1c1c1c/aaaaaa?text=Mank',
    voteAverage: 6.8,
    releaseYear: 2020,
    mediaType: 'movie',
    genres: ['Biography', 'Drama'],
    maturityRating: 'R',
    duration: '2h 11m',
    isNetflixOriginal: true,
    cast: ['Gary Oldman', 'Amanda Seyfried', 'Lily Collins'],
  },
];

export const TOP_RATED_TV: Title[] = [
  {
    id: 14,
    title: 'Dark',
    overview:
      'A missing child sets four families on a frantic hunt for answers as they unearth a mind-bending mystery that spans three generations.',
    posterPath: 'https://via.placeholder.com/300x450/0a0a14/4169e1?text=Dark',
    backdropPath: 'https://via.placeholder.com/1280x720/0a0a14/4169e1?text=Dark',
    voteAverage: 8.8,
    releaseYear: 2017,
    mediaType: 'tv',
    genres: ['Crime', 'Drama', 'Mystery', 'Sci-Fi'],
    maturityRating: 'TV-MA',
    seasons: 3,
    isNetflixOriginal: true,
    cast: ['Louis Hofmann', 'Oliver Masucci', 'Karoline Eichhorn'],
  },
  {
    id: 15,
    title: 'Mindhunter',
    overview:
      'In the late 1970s two FBI agents expand criminal science by delving into the psychology of murder and getting uneasily close to all-too-real monsters.',
    posterPath: 'https://via.placeholder.com/300x450/111111/cc0000?text=Mindhunter',
    backdropPath: 'https://via.placeholder.com/1280x720/111111/cc0000?text=Mindhunter',
    voteAverage: 8.6,
    releaseYear: 2017,
    mediaType: 'tv',
    genres: ['Crime', 'Drama', 'Thriller'],
    maturityRating: 'TV-MA',
    seasons: 2,
    isNetflixOriginal: true,
    cast: ['Jonathan Groff', 'Holt McCallany', 'Anna Torv'],
  },
  {
    id: 16,
    title: 'Narcos',
    overview:
      'A chronicled look at the criminal exploits of Colombian drug lord Pablo Escobar, as well as the many other drug kingpins who plagued the country through the years.',
    posterPath: 'https://via.placeholder.com/300x450/1a3a1a/27ae60?text=Narcos',
    backdropPath: 'https://via.placeholder.com/1280x720/1a3a1a/27ae60?text=Narcos',
    voteAverage: 8.8,
    releaseYear: 2015,
    mediaType: 'tv',
    genres: ['Biography', 'Crime', 'Drama'],
    maturityRating: 'TV-MA',
    seasons: 3,
    isNetflixOriginal: true,
    cast: ['Wagner Moura', 'Boyd Holbrook', 'Pedro Pascal'],
  },
  {
    id: 17,
    title: 'Squid Game',
    overview:
      'Hundreds of cash-strapped players accept a strange invitation to compete in children\'s games. Inside, a tempting prize awaits — with deadly high stakes.',
    posterPath: 'https://via.placeholder.com/300x450/006400/ff0000?text=Squid+Game',
    backdropPath: 'https://via.placeholder.com/1280x720/006400/ff0000?text=Squid+Game',
    voteAverage: 8.0,
    releaseYear: 2021,
    mediaType: 'tv',
    genres: ['Action', 'Drama', 'Mystery', 'Thriller'],
    maturityRating: 'TV-MA',
    seasons: 2,
    isNetflixOriginal: true,
    cast: ['Lee Jung-jae', 'Park Hae-soo', 'Wi Ha-jun'],
  },
  {
    id: 18,
    title: 'Bridgerton',
    overview:
      'Wealth, lust, and betrayal set against the backdrop of Regency Era England, seen through the eyes of the powerful Bridgerton family.',
    posterPath: 'https://via.placeholder.com/300x450/f8e7d3/8b4513?text=Bridgerton',
    backdropPath: 'https://via.placeholder.com/1280x720/f8e7d3/8b4513?text=Bridgerton',
    voteAverage: 7.3,
    releaseYear: 2020,
    mediaType: 'tv',
    genres: ['Drama', 'History', 'Romance'],
    maturityRating: 'TV-MA',
    seasons: 3,
    isNetflixOriginal: true,
    cast: ['Phoebe Dynevor', 'Regé-Jean Page', 'Jonathan Bailey'],
  },
  {
    id: 19,
    title: 'Lupin',
    overview:
      'Inspired by the adventures of Arsène Lupin, gentleman thief Assane Diop sets out to avenge his father for an injustice inflicted by a wealthy family.',
    posterPath: 'https://via.placeholder.com/300x450/1a1a2e/ffd700?text=Lupin',
    backdropPath: 'https://via.placeholder.com/1280x720/1a1a2e/ffd700?text=Lupin',
    voteAverage: 7.5,
    releaseYear: 2021,
    mediaType: 'tv',
    genres: ['Crime', 'Drama', 'Mystery'],
    maturityRating: 'TV-MA',
    seasons: 3,
    isNetflixOriginal: true,
    cast: ['Omar Sy', 'Ludivine Sagnier', 'Clotilde Hesme'],
  },
];

export const NEW_RELEASES: Title[] = [
  {
    id: 20,
    title: 'The Diplomat',
    overview:
      'A career diplomat navigates a crisis in the UK while her marriage to a charming ex-ambassador complicates her ascent in the world of international politics.',
    posterPath: 'https://via.placeholder.com/300x450/1c3a5e/4fc3f7?text=The+Diplomat',
    backdropPath: 'https://via.placeholder.com/1280x720/1c3a5e/4fc3f7?text=The+Diplomat',
    voteAverage: 7.6,
    releaseYear: 2023,
    mediaType: 'tv',
    genres: ['Drama', 'Thriller'],
    maturityRating: 'TV-MA',
    seasons: 2,
    isNetflixOriginal: true,
    cast: ['Keri Russell', 'Rufus Sewell', 'David Gyasi'],
  },
  {
    id: 21,
    title: 'Beef',
    overview:
      'A road rage incident between two strangers spirals into an all-consuming feud that threatens to consume their lives and the lives of those around them.',
    posterPath: 'https://via.placeholder.com/300x450/ff6b35/1a1a1a?text=Beef',
    backdropPath: 'https://via.placeholder.com/1280x720/ff6b35/1a1a1a?text=Beef',
    voteAverage: 8.0,
    releaseYear: 2023,
    mediaType: 'tv',
    genres: ['Comedy', 'Drama', 'Thriller'],
    maturityRating: 'TV-MA',
    seasons: 1,
    isNetflixOriginal: true,
    cast: ['Steven Yeun', 'Ali Wong', 'Joseph Lee'],
  },
  {
    id: 22,
    title: 'All Quiet on the Western Front',
    overview:
      'A young German soldier\'s terrifying experiences and harrowing visions of war as he fights on the Western Front of World War I.',
    posterPath: 'https://via.placeholder.com/300x450/4a4a4a/cccccc?text=All+Quiet',
    backdropPath: 'https://via.placeholder.com/1280x720/4a4a4a/cccccc?text=All+Quiet',
    voteAverage: 7.8,
    releaseYear: 2022,
    mediaType: 'movie',
    genres: ['Action', 'Drama', 'War'],
    maturityRating: 'R',
    duration: '2h 28m',
    isNetflixOriginal: true,
    cast: ['Felix Kammerer', 'Albrecht Schuch', 'Aaron Hilmer'],
  },
  {
    id: 23,
    title: 'Glass Onion',
    overview:
      'Tech billionaire Miles Bron invites his friends for a getaway on his private Greek island. When someone turns up dead, Detective Benoit Blanc is put on the case.',
    posterPath: 'https://via.placeholder.com/300x450/f0e68c/8b6914?text=Glass+Onion',
    backdropPath: 'https://via.placeholder.com/1280x720/f0e68c/8b6914?text=Glass+Onion',
    voteAverage: 7.1,
    releaseYear: 2022,
    mediaType: 'movie',
    genres: ['Comedy', 'Crime', 'Mystery'],
    maturityRating: 'PG-13',
    duration: '2h 19m',
    isNetflixOriginal: true,
    cast: ['Daniel Craig', 'Edward Norton', 'Janelle Monáe'],
  },
];

export const MY_LIST_ITEMS: Title[] = [
  TRENDING_NOW[0],
  POPULAR_MOVIES[0],
  TOP_RATED_TV[3],
  NEW_RELEASES[1],
];

export const ALL_TITLES: Title[] = [
  FEATURED_MOVIE,
  ...TRENDING_NOW,
  ...POPULAR_MOVIES,
  ...TOP_RATED_TV,
  ...NEW_RELEASES,
];
