import { Movie, MovieRow } from '@/types';

const movies: Movie[] = [
  {
    id: '1',
    title: 'Galactic Odyssey',
    description: 'A crew of astronauts embarks on a perilous journey through a newly discovered wormhole near Saturn, hoping to find a new home for humanity as Earth faces an extinction-level climate catastrophe.',
    year: '2024',
    rating: 'PG-13',
    duration: '2h 49m',
    matchScore: 98,
    genres: ['Sci-Fi', 'Adventure', 'Drama'],
    thumbnailUrl: 'https://picsum.photos/seed/movie1/400/225',
    backdropUrl: 'https://picsum.photos/seed/movie1backdrop/1920/1080',
    cast: ['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain'],
    director: 'Christopher Nolan',
    badge: 'TOP 10',
    type: 'movie',
  },
  {
    id: '2',
    title: 'The Last Kingdom',
    description: 'In a dystopian future where water has become the most valuable resource, a lone warrior fights to protect the last remaining freshwater source from a ruthless corporate army.',
    year: '2024',
    rating: 'R',
    duration: '2h 12m',
    matchScore: 95,
    genres: ['Action', 'Thriller', 'Sci-Fi'],
    thumbnailUrl: 'https://picsum.photos/seed/movie2/400/225',
    backdropUrl: 'https://picsum.photos/seed/movie2backdrop/1920/1080',
    cast: ['Tom Hardy', 'Charlize Theron', 'Nicholas Hoult'],
    director: 'George Miller',
    type: 'movie',
  },
  {
    id: '3',
    title: 'Midnight in Paris',
    description: 'A struggling novelist on vacation in Paris discovers a magical portal that transports him back to the 1920s, where he meets his literary heroes and falls in love with a woman from another era.',
    year: '2023',
    rating: 'PG-13',
    duration: '1h 34m',
    matchScore: 91,
    genres: ['Romance', 'Fantasy', 'Comedy'],
    thumbnailUrl: 'https://picsum.photos/seed/movie3/400/225',
    backdropUrl: 'https://picsum.photos/seed/movie3backdrop/1920/1080',
    cast: ['Owen Wilson', 'Marion Cotillard', 'Rachel McAdams'],
    director: 'Woody Allen',
    type: 'movie',
  },
  {
    id: '4',
    title: 'Dark Waters',
    description: 'A tenacious attorney uncovers a dark secret that connects a growing number of unexplained deaths to one of the world\'s largest corporations. In the process, he risks everything — his future, his family, and his own life.',
    year: '2024',
    rating: 'PG-13',
    duration: '2h 6m',
    matchScore: 94,
    genres: ['Drama', 'Thriller'],
    thumbnailUrl: 'https://picsum.photos/seed/movie4/400/225',
    backdropUrl: 'https://picsum.photos/seed/movie4backdrop/1920/1080',
    cast: ['Mark Ruffalo', 'Anne Hathaway', 'Tim Robbins'],
    director: 'Todd Haynes',
    type: 'movie',
  },
  {
    id: '5',
    title: 'The Haunting Hour',
    description: 'A family moves into a remote Victorian mansion only to discover that the house holds dark secrets and is inhabited by malevolent spirits that feed on fear and despair.',
    year: '2024',
    rating: 'R',
    duration: '1h 58m',
    matchScore: 87,
    genres: ['Horror', 'Mystery', 'Thriller'],
    thumbnailUrl: 'https://picsum.photos/seed/movie5/400/225',
    backdropUrl: 'https://picsum.photos/seed/movie5backdrop/1920/1080',
    cast: ['Florence Pugh', 'Jack Reynor', 'William Jackson Harper'],
    director: 'Ari Aster',
    type: 'movie',
  },
  {
    id: '6',
    title: 'Velocity',
    description: 'An elite street racer is recruited by an undercover FBI agent to infiltrate a dangerous criminal organization that uses illegal racing as a front for a massive heist operation.',
    year: '2024',
    rating: 'PG-13',
    duration: '2h 21m',
    matchScore: 89,
    genres: ['Action', 'Crime', 'Thriller'],
    thumbnailUrl: 'https://picsum.photos/seed/movie6/400/225',
    backdropUrl: 'https://picsum.photos/seed/movie6backdrop/1920/1080',
    cast: ['Vin Diesel', 'Michelle Rodriguez', 'Tyrese Gibson'],
    director: 'Justin Lin',
    type: 'movie',
  },
  {
    id: '7',
    title: 'The Crown Chronicles',
    description: 'An epic historical drama following the rise and fall of a powerful dynasty across three generations, exploring themes of power, betrayal, love, and sacrifice in medieval Europe.',
    year: '2024',
    rating: 'TV-MA',
    duration: '8 Seasons',
    matchScore: 96,
    genres: ['Drama', 'History', 'Romance'],
    thumbnailUrl: 'https://picsum.photos/seed/show1/400/225',
    backdropUrl: 'https://picsum.photos/seed/show1backdrop/1920/1080',
    cast: ['Olivia Colman', 'Tobias Menzies', 'Helena Bonham Carter'],
    director: 'Peter Morgan',
    type: 'tv',
  },
  {
    id: '8',
    title: 'Stranger Worlds',
    description: 'A group of teenagers in a small town uncover a government conspiracy involving parallel dimensions, supernatural creatures, and a secret laboratory hidden beneath their quiet neighborhood.',
    year: '2024',
    rating: 'TV-14',
    duration: '4 Seasons',
    matchScore: 97,
    genres: ['Sci-Fi', 'Horror', 'Drama'],
    thumbnailUrl: 'https://picsum.photos/seed/show2/400/225',
    backdropUrl: 'https://picsum.photos/seed/show2backdrop/1920/1080',
    cast: ['Millie Bobby Brown', 'Finn Wolfhard', 'Winona Ryder'],
    director: 'The Duffer Brothers',
    type: 'tv',
  },
  {
    id: '9',
    title: 'Breaking Point',
    description: 'A high school chemistry teacher diagnosed with terminal cancer turns to manufacturing and selling drugs to secure his family\'s financial future, descending into the criminal underworld.',
    year: '2023',
    rating: 'TV-MA',
    duration: '5 Seasons',
    matchScore: 99,
    genres: ['Crime', 'Drama', 'Thriller'],
    thumbnailUrl: 'https://picsum.photos/seed/show3/400/225',
    backdropUrl: 'https://picsum.photos/seed/show3backdrop/1920/1080',
    cast: ['Bryan Cranston', 'Aaron Paul', 'Anna Gunn'],
    director: 'Vince Gilligan',
    type: 'tv',
  },
  {
    id: '10',
    title: 'Money Heist: Origins',
    description: 'A mysterious criminal mastermind recruits eight thieves with unique skill sets to carry out the most audacious heist in history — taking hostages inside the Royal Mint of Spain.',
    year: '2024',
    rating: 'TV-MA',
    duration: '5 Parts',
    matchScore: 93,
    genres: ['Crime', 'Action', 'Drama'],
    thumbnailUrl: 'https://picsum.photos/seed/show4/400/225',
    backdropUrl: 'https://picsum.photos/seed/show4backdrop/1920/1080',
    cast: ['Álvaro Morte', 'Úrsula Corberó', 'Itziar Ituño'],
    director: 'Álex Pina',
    type: 'tv',
  },
  {
    id: '11',
    title: 'Quantum Realm',
    description: 'After a freak accident in a particle accelerator, a physicist gains the ability to manipulate time at the quantum level, but discovers that every change to the timeline has catastrophic consequences.',
    year: '2024',
    rating: 'PG-13',
    duration: '2h 15m',
    matchScore: 92,
    genres: ['Sci-Fi', 'Action', 'Adventure'],
    thumbnailUrl: 'https://picsum.photos/seed/movie7/400/225',
    backdropUrl: 'https://picsum.photos/seed/movie7backdrop/1920/1080',
    cast: ['Paul Rudd', 'Evangeline Lilly', 'Michael Douglas'],
    director: 'Peyton Reed',
    type: 'movie',
  },
  {
    id: '12',
    title: 'The Witcher Saga',
    description: 'A mutated monster hunter struggles to find his place in a world where people often prove more wicked than beasts. His destiny is forever entwined with a powerful sorceress and a young princess.',
    year: '2024',
    rating: 'TV-MA',
    duration: '3 Seasons',
    matchScore: 88,
    genres: ['Fantasy', 'Action', 'Adventure'],
    thumbnailUrl: 'https://picsum.photos/seed/show5/400/225',
    backdropUrl: 'https://picsum.photos/seed/show5backdrop/1920/1080',
    cast: ['Henry Cavill', 'Freya Allan', 'Anya Chalotra'],
    director: 'Lauren Schmidt Hissrich',
    type: 'tv',
  },
  {
    id: '13',
    title: 'Neon Nights',
    description: 'In the neon-soaked streets of Neo Tokyo 2087, a cyberpunk detective investigates a series of murders that blur the line between human consciousness and artificial intelligence.',
    year: '2024',
    rating: 'R',
    duration: '1h 47m',
    matchScore: 90,
    genres: ['Sci-Fi', 'Noir', 'Thriller'],
    thumbnailUrl: 'https://picsum.photos/seed/movie8/400/225',
    backdropUrl: 'https://picsum.photos/seed/movie8backdrop/1920/1080',
    cast: ['Ryan Gosling', 'Ana de Armas', 'Harrison Ford'],
    director: 'Denis Villeneuve',
    type: 'movie',
  },
  {
    id: '14',
    title: 'The Diplomat',
    description: 'A career diplomat is thrust into a high-stakes role in London as she navigates a global crisis while managing a tumultuous marriage to a charming and politically ambitious husband.',
    year: '2024',
    rating: 'TV-MA',
    duration: '2 Seasons',
    matchScore: 94,
    genres: ['Drama', 'Political', 'Thriller'],
    thumbnailUrl: 'https://picsum.photos/seed/show6/400/225',
    backdropUrl: 'https://picsum.photos/seed/show6backdrop/1920/1080',
    cast: ['Keri Russell', 'Rufus Sewell', 'David Gyasi'],
    director: 'Debora Cahn',
    type: 'tv',
  },
  {
    id: '15',
    title: 'Jungle Fury',
    description: 'Deep in the Amazon rainforest, a team of scientists discovers an ancient civilization that has remained hidden for thousands of years — and will stop at nothing to stay that way.',
    year: '2024',
    rating: 'PG-13',
    duration: '2h 3m',
    matchScore: 86,
    genres: ['Adventure', 'Action', 'Mystery'],
    thumbnailUrl: 'https://picsum.photos/seed/movie9/400/225',
    backdropUrl: 'https://picsum.photos/seed/movie9backdrop/1920/1080',
    cast: ['Dwayne Johnson', 'Emily Blunt', 'Edgar Ramirez'],
    director: 'Jaume Collet-Serra',
    type: 'movie',
  },
  {
    id: '16',
    title: 'Squid Games: Reloaded',
    description: 'Hundreds of cash-strapped contestants accept an invitation to compete in children\'s games. Inside, a tempting prize awaits — with deadly high stakes.',
    year: '2024',
    rating: 'TV-MA',
    duration: '2 Seasons',
    matchScore: 97,
    genres: ['Thriller', 'Drama', 'Mystery'],
    thumbnailUrl: 'https://picsum.photos/seed/show7/400/225',
    backdropUrl: 'https://picsum.photos/seed/show7backdrop/1920/1080',
    cast: ['Lee Jung-jae', 'Park Hae-soo', 'Wi Ha-jun'],
    director: 'Hwang Dong-hyuk',
    type: 'tv',
  },
];

export function getFeaturedMovie(): Movie {
  return movies[0];
}

export function getAllMovies(): Movie[] {
  return movies.filter((m) => m.type === 'movie');
}

export function getAllTVShows(): Movie[] {
  return movies.filter((m) => m.type === 'tv');
}

export function getMovieRows(): MovieRow[] {
  return [
    {
      id: 'trending',
      title: 'Trending Now',
      movies: movies.slice(0, 8),
    },
    {
      id: 'top10',
      title: 'Top 10 Movies in the US Today',
      movies: movies.filter((m) => m.type === 'movie'),
    },
    {
      id: 'tvshows',
      title: 'Popular TV Shows',
      movies: movies.filter((m) => m.type === 'tv'),
    },
    {
      id: 'action',
      title: 'Action & Adventure',
      movies: movies.filter((m) => m.genres.includes('Action')),
    },
    {
      id: 'scifi',
      title: 'Sci-Fi & Fantasy',
      movies: movies.filter((m) => m.genres.includes('Sci-Fi') || m.genres.includes('Fantasy')),
    },
    {
      id: 'drama',
      title: 'Award-Winning Dramas',
      movies: movies.filter((m) => m.genres.includes('Drama')),
    },
  ];
}
